apiVersion: batch/v1
kind: Job
metadata:
  name:  "spicedb-migration"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: spicedb
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "spicedb-migration"
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: spicedb
    spec:
      tolerations:
        - effect: NoSchedule
          key: eks.amazonaws.com/compute-type
          value: fargate
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["spicedb"]
          args: ["migrate", "head", "--datastore-engine", "postgres", "--datastore-conn-uri", "$(SPICEDB_DATASTORE_CONN_URI)", "--log-level", "DEBUG"]
          env:
            - name: SPICEDB_DATASTORE_CONN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ required "'datastore.connection.uriSecretName' is required" .Values.datastore.connection.uriSecretName }}
                  key: uri
                  optional: false
