{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spicedb.serviceAccountName" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
