name: EventBridge Receiver

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Event Type'
        required: true
        type: string
        default: 'INIT_SCAN_COMPLETE'
      repo:
        description: 'Repository Name'
        required: true
        type: string
      image_tag:
        description: 'ECR Image Tag'
        required: true
        type: string

permissions:
  id-token: write # This is required for requesting the JWT used in the OIDC assume-role call for AWS permissions
  statuses: write # Allows us to write to commit_status on the original pull-request

jobs:
  vuln_report:
    if: github.event.inputs.type == 'INIT_SCAN_COMPLETE'
    runs-on: ubuntu-latest
    steps:
    - name: dispatch trigger
      run: |
        echo "workflow_dispatch ${{ github.event.inputs.type }} -- ${{ github.event.inputs.repo }} -- ${{ github.event.inputs.image_tag }}"
    # - name: Retrieve Findings
    - name: Create status
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.event.inputs.repo }}/statuses/${{ github.event.inputs.image_tag }} \
        --header 'authorization: Bearer ${{ github.token }}' \
        --header 'content-type: application/json' \
        --data '{
          "state": "success",
          "context": "Test Update",
          "target_url": "https://google.com"
          }' \
        --fail
